lecture_3_django/first_django_project/first_django_project/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
]

lecture_3_django/first_django_project/hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),  # this link the empty url with the request of view and assign a name "index"
    path("<str:name>", views.greet, name="greet"),
    path("brian", views.brian, name="brian"),
    path("david", views.david, name="david")
]

lecture_3_django/first_django_project/newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index")
]

lecture_3_django/first_django_project/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

lecture_3_django/first_django_project/hello/models.py
from django.db import models

# Create your models here.

lecture_3_django/first_django_project/newyear/models.py
from django.db import models

# Create your models here.

lecture_3_django/first_django_project/tasks/models.py
from django.db import models

# Create your models here.

lecture_3_django/first_django_project/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.

def index(request):
    """
    Only return a http response of "hello, world"
    :param request: represent the HTTP request that the user made in order to access our server
    :return:
    """
    return render(request, "hello/index.html")  # this folder is in hello/templates/hello/index.html


def brian(request):
    return HttpResponse("Hello, Brian!")


def david(request):
    return HttpResponse("Hello, David!")


# def greet(request, name):
#     """
#     this will be executed when calling /hello/<name>
#     :param request:
#     :param name: name of the person to greet
#     :return:
#     """
#     return HttpResponse(f"Hello, {name.capitalize()}")

def greet(request, name):
    """
    We use the template hello/greet.html in the folder hello/templates/hello and pass it a context with variables
    that the html file can use with {{ }}
    :param request:
    :param name:
    :return:
    """
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

lecture_3_django/first_django_project/newyear/views.py
import datetime

from django.shortcuts import render


# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

lecture_3_django/first_django_project/tasks/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django import forms
from django.urls import reverse


# Create your views here.

# tasks = ["foo", "bar", "baz"] -> Use request.session


# Create a new class for the form
class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")  # Create input field with a label
    priority = forms.IntegerField(label="Priority", min_value=1, max_value=4)


def index(request):
    # In sessions, we can store data that will be shown only for one computer
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })


def add(request):
    """
    This is called every time someone uses the url tasks/add
    :param request:
    :return:

    """
    # When someone try to post to the add page, for example by submitting a form
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():  # True if the form has no errors
            task = form.cleaned_data["task"]  # Obtain the value of the field task (same name that the class' item)
            request.session["tasks"] += [task]  # add the new task to the global list
            return HttpResponseRedirect(reverse("tasks:index"))  # reverse generates an url from a view name
                                                                #HttpResponseRedirect -> redirect user's browser to a different URL
        else:
            # render the same form of the post to show errors
            # in form the field priority (or the one that have an error) has a new element called errorlist that will
            # be shown
            return render(request, "tasks/add.html", {
                "form": form
            })
    return render(request, "tasks/add.html", {
        "form": NewTaskForm()  # When form is used in add.html, a new NewTaskFrom() is created
    })

lecture_3_django/first_django_project/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
    <title>Is it New Years's?</title>
</head>
<body>
    {% if newyear %}
        <h1>YES</h1>
    {% else %}
        <h1>NO</h1>
    {% endif %}
</body>
</html>

lecture_3_django/first_django_project/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Add Task</h1>
    <form action="{% url 'tasks:add' %}" method="post"> <!--when submit button is pressed, view add() is called-->
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

lecture_3_django/first_django_project/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Tasks</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% empty %}
            <li>No tasks.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">Add a New Task</a>
{% endblock %}

lecture_3_django/first_django_project/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tasks</title>
</head>
<body>
  {% block body %}
  {% endblock %}

</body>
</html>