commerce/auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:auction_id>", views.auction, name="auction"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("watchlist/add/<int:auction_id>", views.add_watchlist, name="add_watchlist"),
    path("<int:auction_id>/close", views.close, name="close"),
    path("create", views.create, name="create"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("categories", views.categories, name="categories"),
    path("categories/<int:category_id>", views.category, name="category")
]

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import SET_NULL, SET
from django.db.models.signals import post_save
from django.dispatch import receiver


class User(AbstractUser):
    pass


class Category(models.Model):
    """
    Represent a Category for an auction
    """
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Auction(models.Model):
    """
    Represent a item that to sell in the page
    """
    title = models.CharField(max_length=64)
    description = models.CharField(max_length=1024)
    starting_bid = models.IntegerField()
    picture = models.URLField(blank=True,
                              default="https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/"
                                      "No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png")
    active = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="auctions")
    category = models.ForeignKey(Category, blank=True, null=True, on_delete=SET_NULL, related_name="auctions")

    def __str__(self):
        return f"{self.title}"

    @property
    def actual_bid(self):
        """
        :return: the highest bid for the auction
        """
        return max(Bid.objects.filter(auction=self), key=lambda bid: bid.price)


class Bid(models.Model):
    """
    Represent a offer made from a user in an auction
    """
    price = models.IntegerField()
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="bids")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bids")

    def __str__(self):
        return f"{self.user} - {self.price}"


class Comment(models.Model):
    """
    Comments made on auction listings
    """
    text = models.CharField(max_length=128)
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="comments")

    def __str__(self):
        return f"{self.text} - {self.user} - {self.auction}"


class Watchlist(models.Model):
    """
    A WatchList for each user to store the items that are interested in
    """
    user = models.OneToOneField(to=User,
                                on_delete=models.CASCADE,
                                related_name="watchlist",
                                primary_key=True)
    auctions = models.ManyToManyField(to=Auction, blank=True)

    def __str__(self):
        return f"{self.user} - {self.auctions}"


@receiver(post_save, sender=User)
def create_user_watchlist(sender, instance, created, **kwargs):
    """
    Signal handler to create a Watchlist for a user after user creation.
    """
    if created:
        Watchlist.objects.create(user=instance)

commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import User, Auction, Watchlist, Comment, Bid, Category


class NewAuctionForm(forms.Form):
    """
    Form to create a new Auction
    """

    title = forms.CharField(label="Title", widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(label="Description",
                                  widget=forms.Textarea(attrs={'rows': 3, 'class': 'form-control'}))
    initial_bid = forms.IntegerField(label="Initial Bid", min_value=0,
                                     widget=forms.NumberInput(attrs={'class': 'form-control'}))
    photo_url = forms.URLField(label="Photo URL", required=False,
                               widget=forms.URLInput(attrs={'class': 'form-control'}))
    categories_choices = [(category.id, category.name) for category in Category.objects.all()]
    categories_choices.insert(0, ('', '---------'))
    category = forms.ChoiceField(label="Category", choices=categories_choices,
                                 widget=forms.Select(attrs={'class': 'form-control'}), required=False)


class NewCommentForm(forms.Form):
    """
    Form to create a new comment for an auction
    """
    text = forms.CharField(label="Comments", widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3}))


class NewBidForm(forms.Form):
    """
    Form to post a new bid for an auction
    """
    bid = forms.IntegerField(label="Bid", min_value=0)


def login_view(request):
    """
    View to log in
    """
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    """
    View to log out
    """
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    """
    View to register as user
    """
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")


@login_required
def index(request):
    """
    View to show the active listing
    """
    return render(request, "auctions/index.html", {
        "auctions": Auction.objects.filter(active=True),
    })


@login_required
def create(request):
    """
    View to create a new listing
    """
    if request.method == "POST":
        form = NewAuctionForm(request.POST)
        if form.is_valid():
            title = request.POST.get("title")
            description = request.POST.get("description")
            initial_bid = request.POST.get("initial_bid")
            photo_url = request.POST.get("photo_url")
            category_id = request.POST.get("category")
            category = Category.objects.get(pk=category_id)
            new_auction = Auction(title=title,
                                  description=description,
                                  starting_bid=initial_bid,
                                  picture=photo_url,
                                  user=request.user,
                                  category=category)
            new_auction.save()

            new_bid = Bid(price=initial_bid, auction=new_auction, user=request.user)
            new_bid.save()

            return HttpResponseRedirect(reverse("auctions:auction", args=(new_auction.pk,)))
        else:
            return render(request, "auctions/create.html", {
                "form": form
            })

    return render(request, "auctions/create.html", {
        "form": NewAuctionForm(),
    })


@login_required
def close(request, auction_id):
    """
    View to close an auction
    """
    if request.method == "POST":
        auction = Auction.objects.get(pk=auction_id)
        if request.user == auction.user:
            auction.active = False

        return HttpResponseRedirect(reverse("auctions:auction", args=(auction_id,)))


@login_required
def auction(request, auction_id):
    """
    View to show an action or handle post request as new comment or new bid offer
    """
    comment_form = NewCommentForm()
    bid_form = NewBidForm()
    auction_item = Auction.objects.get(pk=auction_id)
    if request.method == "POST":
        if 'comment_form' in request.POST:
            comment_form = NewCommentForm(request.POST)
            if comment_form.is_valid():
                comment_text = request.POST["text"]
                new_comment = Comment(text=comment_text,
                                      user=request.user,
                                      auction=auction_item)
                new_comment.save()
                comment_form = NewCommentForm()
        if 'bid_form' in request.POST:
            bid_form = NewBidForm(request.POST)
            if bid_form.is_valid():
                auction_bids = auction_item.bids.all()
                higher_bid = max(auction_bids, key=lambda bid: bid.price)
                higher_bid_price = higher_bid.price
                new_bid_price = int(request.POST["bid"])
                if higher_bid_price < new_bid_price:
                    new_bid = Bid(price=new_bid_price,
                                  auction=Auction.objects.get(pk=auction_id),
                                  user=request.user)
                    new_bid.save()
                    bid_form = NewBidForm()
                    add_watchlist(request, auction_id=auction_id)
                else:
                    bid_form.add_error("bid", f"The bid must be higher than {higher_bid_price}")

        if 'close_form' in request.POST:
            if auction_item.user == request.user:
                auction_item.active = False
                auction_item.save()

    user_watchlist = Watchlist.objects.get(pk=request.user)
    auction = Auction.objects.get(pk=auction_id)
    in_watchlist = auction in user_watchlist.auctions.all()
    comments = Comment.objects.filter(auction=auction).order_by("-date")
    categories = Category.objects.all()
    return render(request, "auctions/auction.html", {
        "auction": auction,
        "n_bids": len(auction.bids.all()) - 1,
        "actual_bid": auction.actual_bid,
        "in_watchlist": in_watchlist,
        "comment_form": comment_form,
        "comments": comments,
        "bid_form": bid_form,
        "categories": categories,
    })


@login_required
def watchlist(request):
    """
    View to show the auctions added to the watchlist for a user
    """
    return render(request, "auctions/watchlist.html", {
        "watchlist": request.user.watchlist.auctions.all(),
    })


@login_required
def add_watchlist(request, auction_id):
    """
    Voew to add an auction into the watchlist
    :param request:
    :param auction_id:
    :return:
    """
    auction = Auction.objects.get(pk=auction_id)
    user_watchlist = request.user.watchlist.auctions.all()
    if auction in user_watchlist:
        request.user.watchlist.auctions.remove(auction)
    else:
        request.user.watchlist.auctions.add(auction)
    return HttpResponseRedirect(reverse("auctions:watchlist"))


@login_required
def categories(request):
    """
    View to show the available categories
    """
    return render(request, "auctions/categories.html", context={
        "categories": Category.objects.all()
    })


@login_required
def category(request, category_id):
    """

    :param request:
    :param category_id:
    :return:
    """
    category = Category.objects.get(pk=category_id)
    return render(request, "auctions/index.html", context={
        "auctions": Auction.objects.filter(category=category, active=True),
        "category": category
    })

commerce/auctions/templates/auctions/auction.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="d-flex flex-column">
    <h2 class="p-2">{{ auction.title }}</h2>
    <div class="p-2">
        <img alt="Bootstrap Image Preview" src="{{ auction.picture }}" class="img-fluid"
             style="max-width: 50%; height: auto;"/>
    </div>
    {% if in_watchlist %}
    <a class="p-0" href="{% url 'auctions:add_watchlist' auction.id %}">Remove from watchlist</a>
    {% else %}
    <a class="p-0" href="{% url 'auctions:add_watchlist' auction.id %}">Add to watchlist</a>
    {% endif %}
    <div class="p-2">{{ auction.description }}</div>
    <div class="p-2" style="font-size: 2rem">${{ actual_bid.price }}</div>

    {% if auction.active %}
    <div class="p-2" style="font-size: 0.8rem">
        {% if auction.user == user and actual_bid.user == user%}
        There are not active bids
        {% elif auction.user == user%}
        {{n_bids}} bid(s) so far. {{actual_bid.user}} is winning
        {% elif actual_bid.user == user %}
        {{n_bids}} bid(s) so far. Your bid is the current bid
        {% else %}
        {{n_bids}} bid(s) so far. Auction in progress, place your bid to win.
        {% endif %}
    </div>
    {% endif %}

    <!--Bid form-->
    {% if auction.active %}
        {% if auction.user != user %}
        <form action="{% url 'auctions:auction' auction.id %}" method="post">
            {% csrf_token %}
            <div class="form-group d-flex flex-row m-1 align-items-center">
                <label class="col-form-label m-2">{{ bid_form.bid.label }}</label>
                <div class="m-2">{{ bid_form.bid }}</div>
                <input class="btn btn-primary m-2" type="submit" name="bid_form" value="Place bid">
            </div>
            <div>{{ bid_form.bid.errors }}</div>
        </form>
        {% else %}
        <form action="{% url 'auctions:auction' auction.id %}" method="post">
            {% csrf_token %}
            <div class="form-group d-flex flex-row m-1 align-items-center">
                <input class="btn btn-primary m-2" type="submit" value="Close" name="close_form">
            </div>
        </form>
        {% endif %}
    {% else %}
        {% if auction.user == user and actual_bid.user == user%}
        <p class="p-3 mb-2 w-25 rounded bg-info text-white">Auction closed without bids</p>
        {% elif auction.user == user %}
        <p class="p-3 mb-2 w-25 rounded bg-success text-white">Auction closed. {{ actual_bid.user }} is the winner!</p>
        {% elif actual_bid.user == user %}
        <p class="p-3 mb-2 w-25 rounded bg-success text-white">Auction closed.You are the winner!</p>
        {% else %}
        <p class="p-3 mb-2 w-25 rounded bg-info text-white">Auction closed.Good luck for next time!</p>
        {% endif %}
    {% endif %}

    <!--Comments form-->
    <form action="{% url 'auctions:auction' auction.id %}" method="post">
        {% csrf_token %}
        {{ comment_form.non_field_errors }}
        <div class="form-group row">
            <h2 class="col-sm-1">{{ comment_form.text.label }}</h2>

        </div>
        <div class="form-group row">
            <div class="col-sm-8">
                {{ comment_form.text }}
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-2 offset-sm-7">
                <input class="btn btn-primary" type="submit" name="comment_form">
            </div>
        </div>
        <div class="form-group row">
            {{ comment_form.text.errors }}
        </div>
    </form>
    <div class="form-group row">
        {% for comment in comments %}
        <div class="col-sm-8">
            <div class="card mb-1">
                <div class="card-body">
                    <div class="d-flex justify-content-start mb-1">
                        <h6 class="fw-bold text-primary mb-1">{{ comment.user }}</h6>
                        <p class="text-muted small mb-0 ml-1"> {{ comment.date }}</p>
                    </div>
                    <p class="mt-1 mb-1 pb-1"> {{ comment.text }} </p>
                </div>
            </div>
        </div>
        {% empty %}
        {% endfor %}
    </div>
</div>


{% endblock %}

commerce/auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
<ul>
    {% for category in categories %}
    <li><a href="{% url 'auctions:category' category.id %}">{{ category.name }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

commerce/auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Create Auction</h2>
    <form action="{% url 'auctions:create' %}" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">{{ field.label }}</label>
            <div class="col-sm-5">
                {{ field }}
            </div>
            <div class="col-sm-2">
                {{ field.errors }}
            </div>
        </div>
        {% endfor %}

        <input type="submit">
    </form>
{% endblock %}

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% block body %}
{% if category %}
<h2>{{category}} Active Listings</h2>
{% else %}
<h2>Active Listings</h2>
{% endif %}
<div class="container">
    <div class="row">
        {% for auction in auctions %}

        <div class="col-md-4 p-3 ">
            <div class="card">
                <img src="{{ auction.picture }}" class="card-img-top p-3" style="width: 200px; height: 200px;" alt="Auction Image">
                <div class="card-body">
                    <a href="{% url 'auctions:auction' auction.id%}">
                        <h5 class="card-title">{{ auction.title }}</h5>
                    </a>
                    <p class="card-text">{{ auction.description }}</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Price: ${{ auction.actual_bid.price }}</small>
                </div>
            </div>
        </div>
        {% empty %}
        No auctions.
        {% endfor %}

    </div>
</div>
{% endblock %}

commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Auctions{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
</head>
<body>
<h1>Auctions</h1>
<div>
    {% if user.is_authenticated %}
    Signed in as <strong>{{ user.username }}</strong>.
    {% else %}
    Not signed in.
    {% endif %}
</div>
<ul class="nav">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'auctions:create' %}">Create Listing</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'auctions:watchlist' %}">
            Watchlist <span class="badge badge-dark">{{ watchlist_count }}</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
    </li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
    </li>
    {% endif %}
</ul>
<hr>
{% block body %}
{% endblock %}
</body>
</html>

commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

commerce/auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}
{% block body %}
<h2>Watchlist</h2>
<ul>
    {% for auction in watchlist %}

    <div class="container-fluid">
        <div class="row mb-4">
            <div class="col-md-2">
                <img alt="Bootstrap Image Preview" src="{{ auction.picture }}" class="img-fluid"/>
            </div>
            <div class="col-md-10">
                <a href="{% url 'auctions:auction' auction.id%}">
                    <h3 class="text-left">{{ auction.title }}
                    </h3>
                </a>
                <p> {{ auction.description }}</p>
                <ul>
                    <li>
                        Initial Bid: {{ auction.starting_bid }}
                    </li>
                </ul>
            </div>
        </div>
    </div>
    {% empty %}
    No auctions.
    {% endfor %}
</ul>
{% endblock %}