project_1/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry_name>", views.entry, name="entry"),
    path("search/", views.search, name="search"),
    path("new_page/", views.new_page, name="new_page"),
    path("edit_page/<str:entry_name>", views.edit_page, name="edit_page"),
    path("random_page/", views.random_page, name="random_page")
]

project_1/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

project_1/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

project_1/wiki/encyclopedia/views.py
import os
import random

import markdown
from django.shortcuts import render
from . import util
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse


class NewPageForm(forms.Form):
    title = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Page Title'})
    )
    content_markdown = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Add a Markdown'})
    )


class EditPageForm(forms.Form):
    content_markdown = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Add a Markdown'}),
        initial="This is a predefined text"
    )


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def entry(request, entry_name):
    entry_markdown = util.get_entry(entry_name)
    entry_html = ""
    if entry_markdown:
        entry_html = markdown.markdown(entry_markdown)

    return render(request, "encyclopedia/entry.html", {
        "entry_html": entry_html,
        "entry_name": entry_name
    })


def search(request):
    query = request.POST.get('query', '')
    available_entries = util.list_entries()
    # The search matches one of the wikipedia pages
    if query in available_entries:
        return entry(request, query)
    # The search is a substring of one or more of the wikipedia pages
    possible_entries = [available_entry for available_entry in available_entries if query in available_entry]
    return render(request, "encyclopedia/search.html", {
        "entries": possible_entries
    })


def new_page(request):
    if request.method == "POST":
        form = NewPageForm(request.POST)
        # Form is not valid
        if not form.is_valid():
            return render(request, "encyclopedia:new_page.html", {
                "form": form
            })
        title = form.cleaned_data["title"]
        # Page already exist
        if title in util.list_entries():
            form.add_error("title", "This page already exist")
            return render(request, "encyclopedia/new_page.html", {
                "form": form
            })
        # Create page
        content_markdown = form.cleaned_data["content_markdown"]
        util.save_entry(title, content_markdown)
        return HttpResponseRedirect(reverse(f"encyclopedia:entry", kwargs={'entry_name': title}))

    return render(request, "encyclopedia/new_page.html", context={
        "form": NewPageForm()
    })


def edit_page(request, entry_name):
    if request.method == "POST":
        form = EditPageForm(request.POST)
        if not form.is_valid():
            return render(request, "encyclopedia/edit_page.html", {
                "form": form,
                "entry_name": entry_name
            })
        content_markdown = form.cleaned_data["content_markdown"]
        util.save_entry(entry_name, content_markdown)
        return HttpResponseRedirect(reverse(f"encyclopedia:entry", kwargs={'entry_name': entry_name}))

    entry_content = util.get_entry(entry_name)
    edit_entry_form = EditPageForm()
    edit_entry_form.fields["content_markdown"].initial = entry_content
    return render(request, "encyclopedia/edit_page.html", {
        "form": edit_entry_form,
        "entry_name": entry_name
    })


def random_page(request):
    entries = util.list_entries()
    random_entry = random.choice(entries)
    return HttpResponseRedirect(reverse(f"encyclopedia:entry", kwargs={'entry_name': random_entry}))

project_1/wiki/encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Edit Page {{ entry_name }}</h1>

    <div class="col-md-8">
    <form action="{% url 'encyclopedia:edit_page' entry_name %}" method="post">
        {% csrf_token %}
        {{ form }}

        <div class="form-group">
            <input class="btn btn-primary" type="submit" value="Submit">
        </div>
    </form>
    </div>

{% endblock %}

project_1/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry_name }}
{% endblock %}

{% block body %}
    {% if entry_html %}
        {{ entry_html|safe|escape }}
        <a href="{% url 'encyclopedia:edit_page' entry_name%}">edit</a>
    {% else %}
        <h1>The page {{ entry_name }} was not found</h1>
    {% endif %}
{% endblock %}

project_1/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry  %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

project_1/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="query" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new_page' %}">Create New Page</a>

                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>

                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

project_1/wiki/encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>

    <div class="col-md-8">
    <form action="{% url 'encyclopedia:new_page' %}" method="post">
        {% csrf_token %}
        {{ form }}

        <div class="form-group">
            <input class="btn btn-primary" type="submit" value="Submit">
        </div>
    </form>
    </div>

{% endblock %}

project_1/wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry  %}">{{ entry }}</a></li>
        {% empty %}
            <li>No results.</li>
        {% endfor %}
    </ul>

{% endblock %}